### ISSUE TITLE
Master branch missing?

### ISSUE THREAD

**Issue by janmyler** [rommguy/react-custom-scroll#1]
It's a really nice component, I only have a few questions.

1) There is no master branch so the download from your Github page doesn't work.
2) Could we separate the component into a NPM (and/or Bower) package?
3) Could we add support for ES2015 or CommonJS modules?
4) Could we drop the jQuery dependency?

Let me know, will be happy to help.

**Comment by rommguy** [comment]
Sorry for the late response, I just now published first stable version to npm so it is officially open source
About your questions - 
1) no need for master branch, just use the gh-pages branch, it is the only one and works like master (it is just a name, master branch isn't special in any way)
2) Done - you can use this with npm. Just install and make sure to take the css too, not just the js file
It is in commonJS format, and there is also a UMD format if you need
3) done - same as previous answer. About ES2015 - I can do that, since the build now uses webpack, but it won't improve any functionality - do you mean readability ?
4) Dropping jQuery - I'm checking, it's mainly there for the events
You can create a pull request without jQuery, I'll be happy to look and merge

**Comment by rommguy** [comment]
Sorry, I can't drop the jQuery dependency right now, it is possible in theory but there is something wrong with the events in IE when I use regular addEventListener to the document
