### ISSUE TITLE
Support of rem width

### ISSUE THREAD

**Issue by christophediprima** [rommguy/react-custom-scroll#18]
Hello,

I am having issues with the native scrollbar being visible in chrome windows depending of the width of the element to scroll. 

I use Zurb Foundation and the grid system uses rem to set the width of the rows and columns.

Sometimes the width is a float and right: 0 + margin-right: -17px is not enough to fully hide the scrollbar.

I fixed this by setting right to -1px but I am not convinced by this fix has the scrolled content will be hidden a bit.

**Comment by rommguy** [comment]
Hi,
Glad to see that you're using this component.
Can you send a link to an example?
It's hard for me to understand without seeing the layout

**Comment by rommguy** [comment]
@christophediprima is this resolved for you?
I'd really like to see an example to be able to help
I think you a fix for this can be to set a default size for the native scroll bigger than 17, instead of calculating it. I can always use 20px like I do in mac when the native scrollbar only appears while scrolling
What do you think ?

**Comment by rommguy** [comment]
Closed due to inactivity
