### ISSUE TITLE
How can i do horizontal scroll ?

### ISSUE THREAD

**Issue by Deepak2322** [rommguy/react-custom-scroll#22]

**Comment by rommguy** [comment]
@Deepak2322 do you need both vertical and horizontal or just horizontal in your app ?

**Comment by Deepak2322** [comment]
I have implemented vertical scroll but can't get horizontal scroll working. I have a list of seats where a user should be able to scroll horizontally and select seat's, so I want the scroll to be always visible to indicate the scrollable content.

**Comment by rommguy** [comment]
I tried supporting both cases, but it was pretty complex, since height and width calculations were effected when there is horizontal scroll, and it's a very rare feature. 
Currently custom-scroll only supports vertical scroll, but you're welcome to contribute and create a pull request to add horizontal as well.
