### ISSUE TITLE
First scroll and last scroll discontinuous

### ISSUE THREAD

**Issue by qoalu** [rommguy/react-custom-scroll#26]
Having a weird issue where during last and first scrolling actions the scrollbar does not animate but moves instantly to the top/bottom.

What could be the reason for this?

EDIT: actually the whole content, not just the scrollbar

**Comment by rommguy** [comment]
@qoalu you're using allowOuterScroll=false right ?

**Comment by qoalu** [comment]
yes, using default value here. 
Please see here 
`http://qoalu.com/storybook-static974u8sakrh283/?selectedKind=Chatter%20Module&selectedStory=KW%20Research%20Sonar&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel`

**Comment by rommguy** [comment]
Well, in this case it looks like you don't need to  block the outer scroll so you can use allowOuterScroll=true.
This will prevent the problem. Here is an explanation why it happens - 
The problem you described is a result of the way I block outer scroll. To block outer scroll, you must call preventDefault() on the scroll event, when you identify it will cause outer scroll (reached the end of the content)
Problem is, you don't know exactly which scroll event will start the outer scroll, because different browsers create different delta values on the event.
So just before reaching the top or bottom ends of the scrolling area, I cancel the scroll event and move the scroll position to the top or bottom accordingly, by setting scrollTop value. This is why the last part of the scrolling isn't native OS scroll animation.

**Comment by qoalu** [comment]
ahh, now I get it. Thanks for explaining. Setting value to true fixed the issue 👍
